# Generated by Django 4.0.5 on 2022-07-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_aletrado_post_criado_post_publicado_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aletrado',
            new_name='alterado',
        ),
    ]
